### ISSUE TITLE
Support for explicitly specified row heights

### ISSUE THREAD

**Issue by telamonian** [finos/regular-table#122]
### Description of Problem:

As per the conversation [here](https://github.com/jupyterlab/team-compass/issues/122), one interesting feature that `@lumino/datagrid` has that `regular-table` is currently lacking is support for explicitly specifying row height.

For at least some set of possible "fat" rows (eg double-height, img with set height, etc), it seems reasonable that the `<regular-table>` author would know in advance what the "height anomaly" would be for a given row. It would be neat if we could support this use case.

### Potential Solutions:

The ideal solution would allow for:
- correct calculation of virtual scroll position, such that there is parity in behavior, thumb size, etc between the virtual scrollbar of a `<regular-table>` and the scrollbar of an eagerly rendered vanilla `<table>`
- preservation of current `regular-table` virtual rendering, in which only the for-real visible rows get rendered

As implemented in `datagrid`, the idea is that you can deal with the various complications introduced by variable row height in **`O(n)`** time, where `n` is the count of rows with custom heights that are affected by a given operation (eg [see here](https://github.com/jupyterlab/lumino/blob/master/packages/datagrid/src/sectionlist.ts#L100-L104)). For rendering, `n` would only be the count of currently visible non-default-height rows.

### Non-solutions:

This feature is distinct from the bug discussed in #96, whereby if any row is larger than the default `19px` it causes the breakage of the calculation of number of rows to render. The solution for #96 just has to prevent the complete breakage of an affected `<regular-table>` (eg it doesn't have to completely fix the virtual scroll behavior, etc). Also hopefully there will be a reasonable solution for #96 that won't require explicitly known/specified heights

**Comment by timkpaine** [comment]
https://github.com/finos/regular-table/pull/191
