### ISSUE TITLE
default yarn install fails

### ISSUE THREAD

**Issue by heswell** [finos/regular-table#181]
### Steps to Reproduce:
run 
```bash
yarn
```

Postinstall task of `sharp` (dependency of `literally-cli` tries to run native build of vips, fails for me(macos)

../src/common.cc:23:10: fatal error: 'vips/vips8' file not found

I can install with `--ignore-scripts` and go on to `yarn build` and all seems ok

**Comment by texodus** [comment]
Thanks for the report, this is fixed on master.

To clarify the title, this is a `devDependencies` linked package, and only applies when trying to build `regular-table` from the source repo on arm64.  `regular-table` has no runtime `dependencies` and this issue doesn't impact using the library as a dependency in your own projects.
