### ISSUE TITLE
support for editable enum cell type

### ISSUE THREAD

**Issue by jgunstone** [finos/regular-table#216]
### Description of Problem:
What *problem* are you trying to solve that the project doesn't currently solve?

regular-table has cell edit functionality which is very powerful. 
A use case that I have (/many people have) is the ability to restrict the user to a dropdown list of allowed options. 
I created this issue here: https://github.com/finos/perspective/issues/2312
and it didn't get much traction. My understanding (though I may be wrong?) is that the solution would probably need implementing here for [perspective](https://github.com/finos/perspective) to be able to make use of it?

### Potential Solutions:
Something like this: 
![image](https://github.com/user-attachments/assets/071ea41f-8919-48f5-9e99-b664f345c795)
https://lumino.readthedocs.io/en/latest/examples/datagrid/index.html

**Comment by texodus** [comment]
[`regular-table` already supports arbitrary HTML cell content](https://github.com/finos/regular-table?tab=readme-ov-file#addstylelistener-and-getmeta-styling).
